import React, { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Activity, Building2, CalendarDays, CheckCircle2, IndianRupee, ListTodo, Loader, MapPin, Phone, Target, TrendingDown, TrendingUp, UserPlus, Users, Zap } from "lucide-react";
import api from "../../services/api";
import { toErrorMessage } from "../../utils/errorMessage";
import ToastNotice from "../../components/ui/ToastNotice";

const STAGES = [
  ["NEW", "New", ListTodo, "#3478f6", "#eef4ff"], ["CONTACTED", "Contacted", Phone, "#3489f6", "#edf6ff"],
  ["INTERESTED", "Interested", Users, "#16a76b", "#ecfaf4"], ["SITE_VISIT", "Visit", CalendarDays, "#f59e0b", "#fff8e8"],
  ["REQUESTED", "Requested", Activity, "#ff5b4d", "#fff0ef"], ["CLOSED", "Closed", CheckCircle2, "#20b978", "#eefaf5"],
];
const money = (v) => Number(v) >= 100000 ? `₹ ${(Number(v) / 100000).toFixed(1)}L` : `₹ ${Number(v || 0).toLocaleString("en-IN")}`;
const dateOf = (v) => { const d = v ? new Date(v) : null; return d && !Number.isNaN(d.getTime()) ? d : null; };
const initials = (name = "") => name.split(/\s+/).slice(0, 2).map((x) => x[0]).join("").toUpperCase() || "NA";
const Card = ({ title, action, children, className = "" }) => <section className={`overflow-hidden rounded-xl border border-[#e2e8f4] bg-white shadow-[0_5px_20px_rgba(35,58,116,.05)] ${className}`}><header className="flex h-12 items-center justify-between border-b border-[#e9edf5] px-4"><h2 className="text-[14px] font-bold text-[#101936]">{title}</h2>{action}</header>{children}</section>;
const Link = ({ children, onClick }) => <button type="button" onClick={onClick} className="text-[11px] font-semibold text-[#1747e8] hover:underline">{children} →</button>;

const ManagerDashboard = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [leads, setLeads] = useState([]), [inventory, setInventory] = useState([]), [users, setUsers] = useState([]);
  const user = useMemo(() => { try { return JSON.parse(localStorage.getItem("user") || "null"); } catch { return null; } }, []);
  useEffect(() => { let live = true; Promise.all([api.get("/leads"), api.get("/inventory"), api.get("/users", { params: { pagination: "false", fields: "_id,name,role,isActive" } })]).then(([a,b,c]) => { if (!live) return; setLeads(a.data?.leads || []); setInventory(b.data?.assets || []); setUsers(c.data?.users || []); }).catch((e) => live && setError(toErrorMessage(e, "Failed to load dashboard"))).finally(() => live && setLoading(false)); return () => { live = false; }; }, []);
  const d = useMemo(() => {
    const count = (s) => inventory.filter((x) => String(x.status).toUpperCase() === s).length;
    const total = inventory.length, available = count("AVAILABLE"), blocked = count("BLOCKED"), maintenance = count("MAINTENANCE"), occupied = Math.max(total - available - blocked - maintenance, 0);
    const closed = leads.filter((x) => String(x.status).toUpperCase() === "CLOSED"), open = leads.filter((x) => String(x.status).toUpperCase() !== "CLOSED");
    const revenue = closed.reduce((s,x) => s + Number(x?.dealPayment?.amount || x?.saleDetails?.amount || 0), 0), now = new Date();
    const follow = leads.map((x) => ({...x, when: dateOf(x.nextFollowUp)})).filter((x) => x.when?.toDateString() === now.toDateString()).sort((a,b) => a.when-b.when).slice(0,4);
    const upcoming = leads.map((x) => ({...x, when: dateOf(x.nextFollowUp || x.siteVisitDate)})).filter((x) => x.when >= now).sort((a,b) => a.when-b.when).slice(0,3);
    const recent = [...leads].sort((a,b) => (dateOf(b.updatedAt)?.getTime() || 0) - (dateOf(a.updatedAt)?.getTime() || 0)).slice(0,4);
    const stages = STAGES.map(([key,label,icon,color,soft]) => ({ key,label,icon,color,soft,value: leads.filter((x) => String(x.status).toUpperCase() === key).length }));
    return { total,available,blocked,maintenance,occupied,occupancy: total ? Math.round(occupied/total*100) : 0,closed,open,revenue,follow,upcoming,recent,stages };
  }, [inventory, leads]);
  if (loading) return <div className="grid h-full place-items-center bg-[#f6f8fc]"><span className="flex items-center gap-2 text-sm text-slate-600"><Loader className="animate-spin" size={18}/>Loading dashboard...</span></div>;
  const hour = new Date().getHours(), greeting = hour < 12 ? "Good Morning" : hour < 17 ? "Good Afternoon" : "Good Evening", max = Math.max(...d.stages.map((x) => x.value), 1);
  const segments = [["Available",d.available,"#19b977"],["Occupied",d.occupied,"#3478f6"],["Blocked",d.blocked,"#f5a623"],["Under Maintenance",d.maintenance,"#ff5f55"]]; let offset = 0;
  const action = (path, text = "View All") => <Link onClick={() => navigate(path)}>{text}</Link>;
  return <div className="h-full overflow-y-auto bg-[#f6f8fc] px-4 py-4 text-[#101936] sm:px-5 lg:px-6"><ToastNotice message={error} type="error"/><div className="mx-auto max-w-[1500px] space-y-4">
    <header><h1 className="text-[23px] font-bold tracking-[-.02em]">{greeting}, {user?.name || "Admin"} 👋</h1><p className="mt-0.5 text-[12px] text-[#607094]">Here&apos;s what&apos;s happening with your workspace today.</p></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[
      ["Total Properties",d.total,"Active in portfolio",Building2,"#1747e8","#eaf0ff",false,"/inventory"],
      ["Total Clients",d.closed.length,"Across all locations",Users,"#1747e8","#edf2ff",false,"/coworking/clients"],
      ["Current Occupancy",`${d.occupancy}%`,`${d.occupied}/${d.total || 0} units occupied`,Target,"#1747e8","#edf2ff",false,"/inventory"],
      ["Open Leads",d.open.length,`${d.stages.find(x=>x.key==="INTERESTED")?.value || 0} interested`,Activity,"#ff574c","#fff0ef",true,"/leads"],
      ["Monthly Revenue",money(d.revenue),"Expected this month",IndianRupee,"#0aa86f","#e8f8f2",false,"/finance"],
    ].map(([label,value,help,IconComponent,color,bg,down,to]) => <button key={label} type="button" onClick={() => navigate(to)} className="flex min-h-[108px] items-start gap-3 rounded-xl border border-[#e2e8f4] bg-white p-3 text-left shadow-[0_5px_20px_rgba(35,58,116,.05)] transition hover:-translate-y-0.5 hover:shadow-md"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl" style={{color,background:bg}}>{React.createElement(IconComponent, { size: 22 })}</span><span className="min-w-0 pt-0.5"><span className="block text-[12px] text-[#54658c]">{label}</span><span className="mt-1 flex items-end gap-2"><strong className="text-[23px] leading-none">{value}</strong><small className={`flex items-center gap-0.5 font-semibold ${down ? "text-red-500":"text-emerald-600"}`}>{down?<TrendingDown size={12}/>:<TrendingUp size={12}/>} {down?"6%":"8%"}</small></span><span className="mt-2 block truncate text-[11px] text-[#526184]">{help}</span></span></button>)}</section>
    <section className="grid gap-4 xl:grid-cols-[1.7fr_1.05fr_1.05fr]">
      <Card title="🏢  Occupancy Overview" action={<select className="h-8 rounded-lg border border-[#dfe5f0] bg-white px-3 text-[11px]"><option>Last 6 Months</option></select>}><div className="relative h-[235px] p-4"><div className="absolute inset-x-12 inset-y-7 grid grid-rows-4 border-b border-l border-[#dfe5f0]">{[0,1,2,3].map(i=><span key={i} className="border-t border-[#e7ebf3]"/>)}</div><svg viewBox="0 0 600 190" className="relative h-full w-full" preserveAspectRatio="none"><defs><linearGradient id="occ" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#5d72f2" stopOpacity=".28"/><stop offset="1" stopColor="#5d72f2" stopOpacity="0"/></linearGradient></defs><path d="M15 145L120 115L225 86L330 57L435 57L540 36L585 24L585 178L15 178Z" fill="url(#occ)"/><path d="M15 145L120 115L225 86L330 57L435 57L540 36L585 24" fill="none" stroke="#2458ef" strokeWidth="2"/></svg><div className="absolute bottom-3 left-12 right-5 flex justify-between text-[10px] text-[#607094]">{["Apr","May","Jun","Jul","Aug","Sep"].map(m=><span key={m}>{m}</span>)}</div></div></Card>
      <Card title="♨  Inventory Status" action={action("/inventory")}><div className="flex min-h-[235px] items-center gap-5 p-4"><div className="relative h-32 w-32 shrink-0"><svg viewBox="0 0 42 42" className="h-full w-full -rotate-90">{segments.map(([label,value,color])=>{const n=d.total?value/d.total*100:0,c=<circle key={label} cx="21" cy="21" r="15.9" fill="none" stroke={color} strokeWidth="6" strokeDasharray={`${n} ${100-n}`} strokeDashoffset={-offset}/>;offset+=n;return c;})}</svg><div className="absolute inset-0 grid place-content-center text-center"><strong className="text-xl">{d.total}</strong><small className="text-[10px] text-[#607094]">Total Units</small></div></div><ul className="min-w-0 flex-1 space-y-3">{segments.map(([label,value,color])=><li key={label} className="flex items-center gap-2 text-[11px]"><i className="h-2.5 w-2.5 rounded-full" style={{background:color}}/><span className="flex-1 text-[#53658a]">{label}</span><strong>{value} ({d.total?Math.round(value/d.total*100):0}%)</strong></li>)}</ul></div></Card>
      <Card title="▣  Today&apos;s Follow-ups" action={action("/leads")}><div className="divide-y divide-[#edf0f6] px-4">{d.follow.length?d.follow.map((lead,i)=><button key={lead._id} type="button" onClick={()=>navigate("/leads")} className="flex w-full items-center gap-3 py-2.5 text-left"><span className={`grid h-9 w-9 place-items-center rounded-full text-xs font-bold ${i%2?"bg-violet-100 text-violet-700":"bg-blue-100 text-blue-700"}`}>{initials(lead.name)}</span><span className="min-w-0 flex-1"><b className="block truncate text-[12px]">{lead.name||"Lead"}</b><small className="block truncate text-[10.5px] text-[#607094]">{lead.status?.replace(/_/g," ")}</small></span><time className="text-[10px]">{lead.when.toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})}</time></button>):<p className="py-16 text-center text-xs text-slate-400">No follow-ups today</p>}</div></Card>
    </section>
    <Card title="Pipeline Snapshot"><div className="grid gap-3 p-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{d.stages.map(s=><button key={s.key} type="button" onClick={()=>navigate("/leads")} className="rounded-lg border border-[#e0e6f1] p-3 text-left" style={{background:s.soft}}><span className="flex items-center gap-2 text-[11px] text-[#53658a]">{React.createElement(s.icon, { size: 14, style: { color: s.color } })}{s.label}</span><span className="mt-2 flex items-end justify-between"><strong className="text-lg">{s.value}</strong><small className="text-[10px]">{leads.length?Math.round(s.value/leads.length*100):0}%</small></span><span className="mt-3 block h-2 overflow-hidden rounded-full bg-white/80"><i className="block h-full rounded-full" style={{width:`${s.value/max*100}%`,background:s.color}}/></span></button>)}</div></Card>
    <section className="grid gap-4 xl:grid-cols-[1.15fr_1.5fr_1fr]">
      <Card title="⌁  Recent Activity" action={action("/leads")}><div className="divide-y divide-[#edf0f6] px-4">{d.recent.map((lead,i)=><button key={lead._id} type="button" onClick={()=>navigate("/leads")} className="flex w-full gap-3 py-2.5 text-left"><span className="mt-1 h-2.5 w-2.5 rounded-full bg-blue-500"/><span className="min-w-0 flex-1"><b className="block truncate text-[12px]">{i?lead.status?.replace(/_/g," "):"Lead updated"}</b><small className="block truncate text-[10.5px] text-[#607094]">{lead.name||lead.phone}</small></span><time className="text-[10px]">{dateOf(lead.updatedAt)?.toLocaleDateString("en-IN",{day:"2-digit",month:"short"})}</time></button>)}</div></Card>
      <Card title="▥  Revenue Overview" action={<select className="h-8 rounded-lg border border-[#dfe5f0] bg-white px-3 text-[11px]"><option>This Year</option></select>}><div className="flex h-[220px] items-end gap-4 px-7 pb-6 pt-5">{[18,26,38,54,59,67,78,91,100].map((h,i)=><div key={i} className="flex h-full flex-1 flex-col justify-end gap-2"><div className="rounded-t bg-gradient-to-t from-[#70d7b3] to-[#a5ead2]" style={{height:`${h}%`}}/><span className="text-center text-[9px] text-[#607094]">{["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep"][i]}</span></div>)}</div></Card>
      <div className="space-y-4"><Card title="Upcoming Visits" action={action("/calendar","View Calendar")}><div className="divide-y divide-[#edf0f6] px-4">{d.upcoming.length?d.upcoming.map(lead=><button key={lead._id} type="button" onClick={()=>navigate("/calendar")} className="flex w-full items-center gap-3 py-2 text-left"><span className="grid h-9 w-12 place-items-center rounded-lg bg-[#eef2fa]"><MapPin size={16} className="text-blue-600"/></span><span className="min-w-0 flex-1"><b className="block truncate text-[11.5px]">{lead.projectInterested||lead.name}</b><small className="text-[10px] text-[#607094]">{lead.name}</small></span><time className="text-[10px]">{lead.when.toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})}</time></button>):<p className="py-8 text-center text-xs text-slate-400">No upcoming visits</p>}</div></Card><Card title="Quick Actions"><div className="grid grid-cols-2 gap-2 p-3">{[["Add Property",Building2,"/inventory","bg-blue-50 text-blue-700"],["Add Client",UserPlus,"/coworking/clients","bg-emerald-50 text-emerald-700"],["Schedule Visit",CalendarDays,"/calendar","bg-amber-50 text-amber-700"],["Create Task",Zap,"/tasks","bg-violet-50 text-violet-700"]].map(([label,IconComponent,to,cls])=><button key={label} type="button" onClick={()=>navigate(to)} className={`grid min-h-20 place-content-center gap-2 rounded-xl text-[11px] font-semibold ${cls}`}>{React.createElement(IconComponent, { size: 20, className: "mx-auto" })}{label}</button>)}</div></Card></div>
    </section>
    <p className="pb-2 text-right text-[10px] text-slate-400">{users.filter(x=>x?.isActive!==false).length} active team members</p>
  </div></div>;
};
export default ManagerDashboard;
